authentication/urls.py
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.urls import path
from . import views
from . forms import *
from django.urls import path, include

app_name = 'authentication'

# Urls for authentication app

urlpatterns = [
	path('register/', views.RegistrationPage.as_view(), name='register-new-user-page'),
	path('login/',
		auth_views.LoginView.as_view(authentication_form=AuthenticationForm, template_name="authentication/login.html"),
		name="login"),
	path('logout/',
		auth_views.LogoutView.as_view(template_name="authentication/login.html"),
		name="logout"),	
    path('reset_password/',
     	auth_views.PasswordResetView.as_view(template_name="authentication/password_reset_form.html", email_template_name="authentication/password_reset_email.html", success_url=reverse_lazy("authentication:password_reset_done")), 
    	name="reset_password",),

    path('reset_password_sent/', 
    	auth_views.PasswordResetDoneView.as_view(template_name="authentication/password_reset_done.html"), 
    	name="password_reset_done"),
    
    path('reset/<uidb64>/<token>/', 
    	auth_views.PasswordResetConfirmView.as_view(template_name="authentication/password_reset_confirm.html", success_url=reverse_lazy("authentication:password_reset_complete") ), 
    	name="password_reset_confirm"),
    
    path('reset_password_complete/', 
    	auth_views.PasswordResetCompleteView.as_view(template_name="authentication/password_reset_complete.html"), 
    	name="password_reset_complete"),	

	path('profile/', views.UserProfile.as_view(), name='user-profile'),

	path('profile/<str:pk>/', views.ViewProfilePage.as_view(), name='user-view-profile'),

    path('profile/<str:pk>/ajax/', views.ViewProfilePageAJAX.as_view()),
]

bowcraftorg/urls.py
from django.contrib import admin
from django.urls import path, include
# doing data because need to set up static url
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, re_path


# rest framework
from rest_framework import routers

from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
# from ckeditor_uploader import views as ckeditor_views

# This file is main file for our project urls

# rest framework
router = routers.DefaultRouter()

# Here we have url paths to all our applications

# Apps, that we are using: admin app, authenication, forum, mainappp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/', include('django_admin_filter.urls')),
    path('', include('mainapp.urls')),
    path('user/', include('authentication.urls')),
    path('forum/', include('forum.urls')),
    path('ckeditor/', login_required(include('ckeditor_uploader.urls'))),
    # path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api/', include(router.urls)),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Here we add other paths to our project, like captcha, Mediroot, 404 page

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

def test_404_view(request):
    raise Http404("Page not found")

urlpatterns += [
    path('test-404/', test_404_view, name='test_404_view'),
]

forum/urls.py
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.urls import path
from . import views
from django.urls import path, include

app_name = 'forum'

# All urls routes for forum application
# We can see forum page, create post, update post, delete post, view details of post, search for post, comment, edit delete comment, ajax for post reputation

urlpatterns = [
	path('', views.ForumIndexPage.as_view(), name="forum-index-page"),
	path('create/', views.CreateForumPost.as_view(), name="forum-create-post"),
	path('update/<str:pk>/', views.UpdateForumPost.as_view(), name="forum-update-post"),
	path('delete/<str:pk>/', views.DeleteForumPost.as_view(), name="forum-delete-post"),
	path('post/<str:pk>/', views.DetailForumPage.as_view(), name='forum-detail-page'),
	path('search/', views.fullSearch.as_view(), name='forum-search'),
	path('comment/edit/<str:pk>/', views.EditCommentToPost.as_view(), name='forum-edit-comment-post'),
	path('comment/delete/<str:pk>/', views.DeleteCommentToPost.as_view(), name='forum-delete-comment-post'),
	path('post/<str:pk>/ajax/', views.DetailForumPostPageAjax.as_view()),
]

mainapp/urls.py
from django.urls import path
from . import views

# This file contains all urls for our mainapp

app_name = 'mainapp'

# Home page with presentaion, news page, support us page, download page, individual news post page, contact page
# contact confirm message send page, security report url and security security success message sent
urlpatterns = [
	path('', views.HomePage.as_view(), name='home-page'),
	path('news/', views.NewsPage.as_view(), name='news-page'),
	path('news/all/', views.NewsAllPage.as_view(), name='news-all'),
	path('support/us/', views.SupportUs.as_view(), name='support-us-page'),
	path('download/', views.DownloadPage.as_view(), name='download-page'),
	path('post/<str:pk>/', views.PostDetailPage.as_view(), name='post-detail'),
	path('contact/', views.ContactPage.as_view(), name='contact-page'),
	path('contact/confirm', views.ConfirmPage.as_view(), name='confirm-contact-page'),
	path('security/report', views.SecurityContactPage.as_view(), name='secutiry-report-bug'),
	path('security/success/', views.SuccessSecurityPage.as_view(), name='secutiry-report-success'),
]

authentication/models.py
from django.db import models
from django.contrib.auth.models import User

from forum.models import ForumPost

# In this file we make Database tables for authentication and user profiles

# this is a fix for standard djnago table User
# quick fix to user model, without writing in it
# email must be unique, required and if it is already in db no blow up
User._meta.get_field('email')._unique = True
User._meta.get_field('email').blank = False
User._meta.get_field('email').null = True

# user profile table
class User_Profile(models.Model):
	# add options of gender -> male or female
	GENDER = (
		('Male', 'Male'),
		('Female', 'Female'),
		('Other', 'Other'),	
		)

	user = models.OneToOneField(User, related_name="user_profile", blank=True, null=True, on_delete=models.CASCADE)
	
	date_of_birth = models.DateField(blank=True, null=True)

	gender = models.CharField(max_length=15, null=True, blank=True, choices=GENDER)

	profile_picture = models.ImageField(default="user_default_images/default_user_picture.png", null=True, blank=True)

	description = models.TextField(max_length=450, null=True, blank=True)


	# change reputation to the int field (change datatype + apply reputation schema)
	reputation = models.IntegerField(default="0")

	opinion_posts = models.ManyToManyField(ForumPost, blank=True)


	def __str__(self):
		try:
			return self.user.username
		except:
			print('Something went wrong, while loading user.username, probably, because something missing in database')
			return 'Err'

# reputation table 
class Reputation_user(models.Model):
	# Reputaion giver
	appraiser = models.ForeignKey(User, related_name="Appraiser_to_Usermodel", on_delete=models.CASCADE)
	# User who recieves reputation
	assessed = models.ForeignKey(User, related_name="Assessed_to_ForumPost", on_delete=models.CASCADE)
	
	reputation = models.IntegerField(default=0)

	def __str__(self):
		return self.appraiser.username + ' | ' + self.assessed.username + ' | ' + str(self.reputation)

authentication/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from . models import *

# in this file we create User form, authentication form, user edit probile form/ We need this to make users able to edit themselves
class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

	def __init__(self, *args, **kwargs):
		super(CreateUserForm, self).__init__(*args, **kwargs)

		for fieldname in ['username', 'password1', 'password2']:
			self.fields[fieldname].help_text = None

class AuthenticationForm(AuthenticationForm):
	class Meta:
		model = User
		fields = ('email', 'password')


class UserProfileForm(ModelForm):
	class Meta:
		model = User	
		fields = ['username', 'first_name', 'last_name']


class ProfileUserForm(ModelForm):
	class Meta:
		model = User_Profile
		fields = '__all__'
		exclude = ['user', 'reputation', 'opinion_posts']

authentication/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic.edit import FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.contrib import messages

from . models import *
from . forms import *

# View file, that is showing our views for authentication
# registration form view
register_template = 'authentication/registration.html'

class RegistrationPage(View):
	def get(self, request):
		if request.user.is_authenticated:
			return redirect('mainapp:home-page')

		form = CreateUserForm()
		ctx = {
		'form':form,
		}

		return render(request, register_template, ctx)
	def post(self, request):
		form = CreateUserForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('email')
			password = form.cleaned_data.get('password1')
			user_auth = authenticate(username=username, password=password)
			login(request, user_auth)
			# all after form login defined in signals
			
			return redirect('mainapp:home-page')
		else:
			#not refresh the form, because otherwise errors won't be returned
			la = 'hello world'
			ctx = {
			'form':form,
			'hi':la,
			}
			return render(request, register_template, ctx)

# User profile page view. This is view for user for himself, not others. He can edit himself
class UserProfile(LoginRequiredMixin, View):
	def get(self, request):
		user = User.objects.get(pk=request.user.id)
		user_profile = request.user.user_profile
		form1 = UserProfileForm(instance=user)
		form2 = ProfileUserForm(instance=user_profile)
		ctx = {
		'user':user,
		'form1':form1,
		'form2':form2,
		}
		return render(request, 'authentication/user_profile.html', ctx)

	def post(self, request):
		user_profile = request.user.user_profile
		user = User.objects.get(pk=request.user.id)
		form1 = UserProfileForm(request.POST, instance=user)
		form2 = ProfileUserForm(request.POST, request.FILES, instance=user_profile)

		if form1.is_valid() and form2.is_valid():
			form1.save()
			form2.save()
			return redirect('authentication:user-profile')
		else:
			ctx = {
			'form1':form1,
			'form2':form2,
			}
			return render(request, 'authentication/user_profile.html', ctx)

# This is view for other users to be able to view other user
class ViewProfilePage(View):
	def getqueryrelation(self, request, assessed):
		# function that is taking everything that repeating in it. It is checking if user has a query relation with post. If he liked or disliked that post
		# also it checks, if user is authenticated
		if request.user.is_authenticated:
			query_relation = Reputation_user.objects.filter(appraiser=request.user).filter(assessed=assessed).first()
			if query_relation is None:
				relation_value = 0
			else:
				relation_value = query_relation.reputation
		else:
			relation_value = None

		return relation_value

	def get(self, request, pk):
		user_object = User.objects.get(pk=pk)
		ctx={
		'user_object':user_object,
		'relation_value': self.getqueryrelation(request, user_object),
		}
		return render(request, 'authentication/user_profile_view.html', ctx)

# this thing is made with ajax. It is view profile with ajax to be able to edit reputation
# this whole view is made to be able to edit reputation of the concrete user
class ViewProfilePageAJAX(LoginRequiredMixin, View):
	def post(self, request, pk):
		# get the user Entry.objects.get(pk=1)
		appraiser_user = User.objects.get(pk=request.POST["user_appraiser_id"])

		# get assessed user
		assessed_user = User.objects.get(pk=request.POST["user_assessed_id"])

		assessed_user_profile = User_Profile.objects.get(pk=assessed_user.id)

		# get user action
		user_action = request.POST["user_action"]


		if assessed_user.is_staff or assessed_user==appraiser_user:
			return JsonResponse()

		# make a assessment here
		# temp reputation
		if user_action == 'dislike':
			reputation_temp = 1
		else:
			reputation_temp = -1


		# get query relation
		query_relation = Reputation_user.objects.filter(appraiser=appraiser_user).filter(assessed=assessed_user).first()

		counter = 0


		if query_relation == None:
			if user_action == 'like':
				reputation_temp = 1
			elif user_action == 'dislike':
				reputation_temp = -1
			else:
				reputation_temp = 0
			new_relation = Reputation_user(appraiser=appraiser_user, assessed=assessed_user, reputation=reputation_temp)
			
			assessed_user_profile.reputation += new_relation.reputation
			assessed_user_profile.save()
			new_relation.save()
			query_relation = new_relation
		else:
			# so if reputation is greater then 0 we will check if
			if query_relation.reputation > 0:
				# it is like pressed, if so, undo the reputation and lover the people, that have been before
				if user_action == 'like':
					query_relation.reputation += -1
					counter = -1
					
				# if it is dislike, we dont undo the people, but we changing the reputation
				elif user_action == 'dislike':
					query_relation.reputation += -2
					counter = -2
				else:
				# else we do nothing
					pass
			# else if the reputation is negative (means the dislike have been pressed before)
			elif query_relation.reputation < 0:
				# we will check, if it is a like, if so we won't change the count of people, inseted change reputation
				if user_action == 'like':
					query_relation.reputation += 2
					counter += 2
				# if dislike have been pressed the second time, we will undo dislike and lower the people
				elif user_action == 'dislike':
					query_relation.reputation += 1
					
					counter +=1
				# else we do nothing
				else:
					pass
			# if the relation exist and it is 0 and something have been pressed we will change reputation and do nothing with people, because they are counted up
			else:
				if user_action == 'like':
					query_relation.reputation = 1
					counter += 1
					
				elif user_action == 'dislike':
					query_relation.reputation = -1
					
					counter -= 1
				else:
					pass			
			assessed_user_profile.reputation += counter
			assessed_user_profile.save()
			query_relation.save()

		data = {
		
		"reputation" : assessed_user_profile.reputation,
		"current_relation_reputation": query_relation.reputation
		}
		
		return JsonResponse(data)

authentication/templates/authentication/login.html
{% extends 'mainapp/base_template.html' %}
{% load crispy_forms_tags %}

{% block content %}


<article class="article-system">
	<div class="container-fluid pb-4 pt-3">
		<div class="row">
			 <div class="col-sm-5 mx-auto m-2 p-3 mb-3 border article-system-bg-white">
			 	<hr>

				<h2 class="text-primary text-center">Login</h2>
				{% if form.errors %}
					<div class="alert alert-danger" role="alert">
						<ul>
 						 <li>Please enter a correct email and password. Note that both fields <br> may be case-sensitive.</li>
 						</ul>
					</div>
				{% endif %}		
					<form method="POST">
					  {% csrf_token %}
					  <!-- {{form|crispy}} -->

					  <!-- two fields -->
					  <div id="div_id_username" class="form-group"> <label for="id_username" class=" requiredField">
                Email<span class="asteriskField">*</span> </label> <div class=""> <input type="text" name="username"  autofocus autocapitalize="none" autocomplete="username" maxlength="150" class="textinput textInput form-control" required id="id_username"> </div> </div> <div id="div_id_password" class="form-group"> <label for="id_password" class=" requiredField">
                Password<span class="asteriskField">*</span> </label> <div class=""> <input type="password" name="password" autocomplete="current-password" class="textinput textInput form-control" required id="id_password"> </div>
					  <!-- login form -->


					  <input type="hidden" name="next" value="{{ next }}">
					  	<div class="mt-3">
					  		<button type="submit" class="btn btn-primary text-end">Login</button>
						</div>
					</form>
				<hr>
				<br>
				Haven't got an account? <span class="float-end">Forgot a password?</span><br> 
				<a href="{% url 'authentication:register-new-user-page' %}">Login</a>
				<a class="float-end" href="{% url 'authentication:reset_password' %}">Reset password</a>		
		</div>
	</div>
</article>
{% endblock %}

authentication/templates/authentication/password_reset_complete.html
{% extends 'mainapp/base_template.html' %}

{% block content %}
	<article class="article-system">
		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-5 mx-auto m-2 p-3 border article-system-bg-white">
					<hr>
					<h2 class="text-primary text-center">The password has been changed</h2>
						<p>
							<a href="{% url 'authentication:login' %}">login again?</a>
						</p>		
					<hr>			
				</div>
			</div>
		</div>
	</article>

{% endblock %}

authentication/templates/authentication/password_reset_confirm.html
{% extends 'mainapp/base_template.html' %}

{% block content %}
	<article class="article-system">
		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-5 mx-auto m-2 p-3 border article-system-bg-white">
					<hr>
					<h2 class="text-primary text-center">Change your password</h2>
					<form action="" method="POST">
						{% csrf_token %}
						<div class="mb-3">
					    	<label for="password1" class="form-label">Type new password</label>
					    	<input name="new_password1" type="password" class="form-control" id="password1">
					  	</div>
					  	<div class="mb-3">
					    	<label for="password2" class="form-label">Password Confirm</label>
					    	<input name="new_password2" type="password" class="form-control" id="password2">
					  	</div>
					  	<button type="submit" class="btn btn-primary text-end">Change your password</button>
					</form>


					{{form.erros}}



					{% if form.errors %}
					    {% for field in form %}
					        {% for error in field.errors %}
					            <div class="alert alert-danger mt-3">
					                {{ error|escape }}
					            </div>
					        {% endfor %}
					    {% endfor %}
					    {% for error in form.non_field_errors %}
					        <div class="alert alert-danger">
					            {{ error|escape }}
					        </div>
					    {% endfor %}
					{% endif %}			
					<hr>			
				</div>
			</div>
		</div>
	</article>

{% endblock %}

authentication/templates/authentication/password_reset_done.html
{% extends 'mainapp/base_template.html' %}

{% block content %}
	<article class="article-system">
		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-5 mx-auto m-2 p-3 border article-system-bg-white">
					<hr>
					<h2 class="text-primary text-center">Check your mailbox</h2>
						<p>
							We've emailed you instructions for setting your password. 
							If they haven't arrived in a few minutes, check your spam folder.
						</p>	
					<hr>			
				</div>
			</div>
		</div>
	</article>

{% endblock %}

authentication/templates/authentication/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'authentication:password_reset_confirm' uidb64=uid token=token %}

authentication/templates/authentication/password_reset_form.html
{% extends 'mainapp/base_template.html' %}

{% block content %}
	<article class="article-system">
		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-5 mx-auto m-2 p-3 border article-system-bg-white">
					<hr>
					<h2 class="text-primary text-center">Password reset is not avaliable now</h2>
					<div class="mb-3">
						<h3>Please go to report issue page, choose the category other and send your issue to us. We will help you to reset your password</h3>

						<a href="{% url 'mainapp:secutiry-report-bug' %}" class="btn btn-primary text-end">Go to report an issue page</a>
					</div>
					{% if form.errors %}
					    {% for field in form %}
					        {% for error in field.errors %}
					            <div class="alert alert-danger mt-3">
					                {{ error|escape }}
					            </div>
					        {% endfor %}
					    {% endfor %}
					    {% for error in form.non_field_errors %}
					        <div class="alert alert-danger">
					            {{ error|escape }}
					        </div>
					    {% endfor %}
					{% endif %}			
					<hr>			
				</div>
			</div>
		</div>
	</article>

{% endblock %}

authentication/templates/authentication/registration.html
{% extends 'mainapp/base_template.html' %}
{% load crispy_forms_tags %}

{% block content %}


<article class="article-system">
	<div class="container-fluid">
		<div class="row">
			 <div class="col-sm-5 mx-auto m-2 p-3 border article-system-bg-white">
			 	<hr>
				<h2 class="text-primary text-center">Registration</h2>
					<form method="POST">
					  {% csrf_token %}
					  {{form|crispy}}
					  
					  	<div class="mt-3">
					  		<button type="submit" class="btn btn-primary text-end">Sign Up</button>
						</div>
					</form>
				<hr>
				Already have an account?<br>
				<a href="{% url 'authentication:login' %}">Sign In</a>
		</div>
	</div>
</article>
{% endblock %}

authentication/templates/authentication/user_profile.html
{% extends 'mainapp/base_template.html' %}
{% load static from static %}
{% load crispy_forms_tags %}

{% block content %}

<article>
	<div class="container-fluid">
		<div class="row">
			{% include 'authentication/user_profile_aside.html' %}
			<div class="col-sm-9 mx-auto m-2 p-3 border article-system-bg-white">
				
				<h2 class="text-primary text-center">Profile Settings</h2>
				<hr>
				<p>Username: {{user.username}}</p>
				<p>Email: {{user.email}}</p>
				<p>Reputation: {{user.user_profile.reputation}}</p>
				
				<form method="POST" action="" enctype="multipart/form-data">
				{% csrf_token %}
				{{form1 | crispy}}
				{{form2 | crispy}}
		
				<input class="btn btn-primary" type="submit" name="Update Information" value="Update changes">
				</form>

			</div>
		</div>
	</div>
</article>





{% endblock %}

authentication/templates/authentication/user_profile_aside.html
<div class="col-sm-3 mx-auto m-2 p-3 border article-system-bg-white">
	<img class="profile-picure-big mx-auto d-block" src="{{user.user_profile.profile_picture.url}}" alt="Profile Image">
	<hr>
	<div class="d-grid gap-0">
			
	</div>

	<div class="btn-group d-grid" role="group" aria-label="Admin panel">
	<div class="btn-group-vertical" role="group" aria-label="Vertical button group">
		{% url 'authentication:user-profile' as url_profile %}
		<a class="btn btn-dark {% if request.path == url_profile %}disabled{% endif %}" type="button" href="{{ url_profile }}">General</a>
			
			<a href="{% url 'authentication:user-view-profile' request.user.id %}" class="btn btn-dark">View Profile</a>
			<a class="btn btn-warning" href="{% url 'authentication:logout' %}">Logout</a>

	</div>
	</div>

</div>

authentication/templates/authentication/user_profile_view.html
{% extends 'mainapp/base_template.html' %}
{% load static from static %}

{% block content %}

<article>
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-1"></div>
			<div class="col-sm-2 mx-auto mt-2 p-3 border article-system-bg-white">
				<img class="profile-picure-big mx-auto d-block" src="{{user_object.user_profile.profile_picture.url}}" alt="Profile Image">
				<hr>
				<div class="d-grid gap-0">
					{% if request.user != user_object %}
					<a href="{% url 'mainapp:secutiry-report-bug' %}" class="btn btn-dark" type="button">Report</a>
					{% endif %}
					<a href="{{request.META.HTTP_REFERER}}" class="btn btn-warning">Go back</a>
				</div>

			</div>
			<div class="col-sm-8 mx-auto mt-2 pb-3 border article-system-bg-white">
				
				<h2 class="pt-2 text-primary text-center">{% if user_object.is_staff %}<i class="fas text-warning fa-crown"></i> {% endif %}{{user_object.username}}{% if user_object.is_staff %}<i class="fas text-warning fa-crown ms-2"></i> {% endif %}</h2>
				<hr>
				{% if request.user.is_authenticated and request.user != user_object and not user_object.is_staff %}
				<div style="float:right;"><a class="btn btn-primary me-2" href="{% url 'mainapp:secutiry-report-bug' %}"><i class="fas fa-exclamation"></i></a>
	    				<button class="btn btn-success d-inline text-nowrap" onclick="onUserThumbs('{{request.user.id}}', '{{user_object.id}}', 'like')"><i id="like" class="{% if relation_value <= 0 %}far{% else %}fas{% endif %} fa-thumbs-up"></i></button><button class="btn btn-danger d-inline text-nowrap" onclick="onUserThumbs('{{request.user.id}}', '{{user_object.id}}', 'dislike')"><i id="dislike" class="{% if relation_value >= 0 %}far{% else %}fas{% endif %} fa-thumbs-down"></i></button></div>
				{% endif %}
				<h4 class="text-info mb-3">Basic information <i class="fas fa-info-circle"></i></h4>
				<p>Nickname: {{user_object.username}}</p>
				<p>Firstname: {{user_object.first_name}}</p>
				<p>Lastname: {{user_object.last_name}}</p>
				<p>Reputation: {% if user_object.is_staff %}<span class="text-danger"><i class="fas fa-user-tie pe-3"></i><u>administrator</u><i class="fas fa-user-tie"></i></span>{% else %}<span id="repa">{{user_object.user_profile.reputation}}</span>{% endif %}</p>
				<p>Description</p>
				<p>{{user_object.user_profile.description}}</p>
				<p class="float-start">Date joined: {{ user_object.date_joined }}</p>
			</div>
			<div class="col-sm-1"></div>
		</div>
	</div>
</article>




{% endblock %}