authentication/urls.py
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.urls import path
from . import views
from . forms import *
from django.urls import path, include

app_name = 'authentication'

# Urls for authentication app

urlpatterns = [
	path('register/', views.RegistrationPage.as_view(), name='register-new-user-page'),
	path('login/',
		auth_views.LoginView.as_view(authentication_form=AuthenticationForm, template_name="authentication/login.html"),
		name="login"),
	path('logout/',
		auth_views.LogoutView.as_view(template_name="authentication/login.html"),
		name="logout"),	
    path('reset_password/',
     	auth_views.PasswordResetView.as_view(template_name="authentication/password_reset_form.html", email_template_name="authentication/password_reset_email.html", success_url=reverse_lazy("authentication:password_reset_done")), 
    	name="reset_password",),

    path('reset_password_sent/', 
    	auth_views.PasswordResetDoneView.as_view(template_name="authentication/password_reset_done.html"), 
    	name="password_reset_done"),
    
    path('reset/<uidb64>/<token>/', 
    	auth_views.PasswordResetConfirmView.as_view(template_name="authentication/password_reset_confirm.html", success_url=reverse_lazy("authentication:password_reset_complete") ), 
    	name="password_reset_confirm"),
    
    path('reset_password_complete/', 
    	auth_views.PasswordResetCompleteView.as_view(template_name="authentication/password_reset_complete.html"), 
    	name="password_reset_complete"),	

	path('profile/', views.UserProfile.as_view(), name='user-profile'),

	path('profile/<str:pk>/', views.ViewProfilePage.as_view(), name='user-view-profile'),

    path('profile/<str:pk>/ajax/', views.ViewProfilePageAJAX.as_view()),
]

bowcraftorg/urls.py
from django.contrib import admin
from django.urls import path, include
# doing data because need to set up static url
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, re_path


# rest framework
from rest_framework import routers

from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
# from ckeditor_uploader import views as ckeditor_views

# This file is main file for our project urls

# rest framework
router = routers.DefaultRouter()

# Here we have url paths to all our applications

# Apps, that we are using: admin app, authenication, forum, mainappp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/', include('django_admin_filter.urls')),
    path('', include('mainapp.urls')),
    path('user/', include('authentication.urls')),
    path('forum/', include('forum.urls')),
    path('ckeditor/', login_required(include('ckeditor_uploader.urls'))),
    # path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api/', include(router.urls)),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Here we add other paths to our project, like captcha, Mediroot, 404 page

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

def test_404_view(request):
    raise Http404("Page not found")

urlpatterns += [
    path('test-404/', test_404_view, name='test_404_view'),
]

forum/urls.py
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.urls import path
from . import views
from django.urls import path, include

app_name = 'forum'

# All urls routes for forum application
# We can see forum page, create post, update post, delete post, view details of post, search for post, comment, edit delete comment, ajax for post reputation

urlpatterns = [
	path('', views.ForumIndexPage.as_view(), name="forum-index-page"),
	path('create/', views.CreateForumPost.as_view(), name="forum-create-post"),
	path('update/<str:pk>/', views.UpdateForumPost.as_view(), name="forum-update-post"),
	path('delete/<str:pk>/', views.DeleteForumPost.as_view(), name="forum-delete-post"),
	path('post/<str:pk>/', views.DetailForumPage.as_view(), name='forum-detail-page'),
	path('search/', views.fullSearch.as_view(), name='forum-search'),
	path('comment/edit/<str:pk>/', views.EditCommentToPost.as_view(), name='forum-edit-comment-post'),
	path('comment/delete/<str:pk>/', views.DeleteCommentToPost.as_view(), name='forum-delete-comment-post'),
	path('post/<str:pk>/ajax/', views.DetailForumPostPageAjax.as_view()),
]

mainapp/urls.py
from django.urls import path
from . import views

# This file contains all urls for our mainapp

app_name = 'mainapp'

# Home page with presentaion, news page, support us page, download page, individual news post page, contact page
# contact confirm message send page, security report url and security security success message sent
urlpatterns = [
	path('', views.HomePage.as_view(), name='home-page'),
	path('news/', views.NewsPage.as_view(), name='news-page'),
	path('news/all/', views.NewsAllPage.as_view(), name='news-all'),
	path('support/us/', views.SupportUs.as_view(), name='support-us-page'),
	path('download/', views.DownloadPage.as_view(), name='download-page'),
	path('post/<str:pk>/', views.PostDetailPage.as_view(), name='post-detail'),
	path('contact/', views.ContactPage.as_view(), name='contact-page'),
	path('contact/confirm', views.ConfirmPage.as_view(), name='confirm-contact-page'),
	path('security/report', views.SecurityContactPage.as_view(), name='secutiry-report-bug'),
	path('security/success/', views.SuccessSecurityPage.as_view(), name='secutiry-report-success'),
]

forum/models.py
from django.db import models
from django.contrib.auth.models import User

# from ckeditor_uploader.fields import RichTextUploadingField
from django_ckeditor_5.fields import CKEditor5Field
from django.conf import settings

from taggit.managers import TaggableManager

# This file contains database for our forum post and comments to our posts. As well there are functionality for reputation

class ForumPost(models.Model):
	CATEGORY = (
		('Important', 'Important'),
		('Suggestions', 'Suggestions'),
		('Help', 'Help'),
		('Question','Question'),
		('Discussion', 'Discussion'),
		('Other', 'Other'),
	)
	# user is already in here defined for owner.py
	user = models.ForeignKey(User, related_name="user_post", blank=True, null=True, on_delete=models.CASCADE)
	name = models.CharField(max_length=30, null=True)
	topic = models.CharField(max_length=100, null=True, choices=CATEGORY)
	tags = TaggableManager(blank=True)
	
	content = CKEditor5Field(null=True, blank=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True)
	post_reputation = models.IntegerField(default=0)
	people_voted = models.IntegerField(default=0)

	def __str__(self):
		return self.topic + ' ' + self.name 

class CommentToPost(models.Model):
	user = models.ForeignKey(User, related_name="user_comment", blank=True, null=True, on_delete=models.CASCADE)
	post = models.ForeignKey(ForumPost, related_name="post_comment", blank=True, null=True, on_delete=models.CASCADE)
	text = models.TextField(null=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True)

	def __str__(self):
		return self.post.name + ' ' + self.user.username + ' ' + str(self.date_created) + ' ' + str(self.id)


class Reputation_post(models.Model):

	user = models.ForeignKey(User, related_name="reputation_to_Usermodel", on_delete=models.CASCADE)
	post = models.ForeignKey(ForumPost, related_name="reputation_to_ForumPost", on_delete=models.CASCADE)
	reputation = models.IntegerField(default=0)

	def __str__(self):
		return self.post.name + ' | ' + self.user.username + ' | ' + str(self.reputation)

forum/forms.py
from django import forms
from django.forms import ModelForm
from crispy_forms.helper import FormHelper
from . models import *

# This forms file contains forum creation and comment creation functionality

# Here we have functionality to be able to create post for forum
class ForumPostForm(ModelForm):
	class Meta:
		model = ForumPost
		fields = ['name', 'topic', 'tags', 'content']

# This is functionality to be able to create comment for post
class CommentToPostForm(ModelForm):
	text = forms.CharField(widget=forms.Textarea, label='')
	class Meta:
		model = CommentToPost
		fields = ['text']

forum/views.py
from django.shortcuts import render, redirect
from django.views import View, generic
from django.views.generic.edit import FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.contrib.auth import authenticate, login
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.views.generic import DetailView

from itertools import chain

from . models import *
from . forms import *
from . owner import *
from . filters import *

# This view file contains functionality for all our forum app

# protect delete and update views
class ForumIndexPage(generic.ListView):
	template_name = 'forum/forum_index.html'
	paginate_by = 20
	model = ForumPost
	def get_queryset(self):
		posts = ForumPost.objects.all()
		# filter all usernames
		queryset = super(ForumIndexPage, self).get_queryset()

		self.myFilter = ForumFilter(self.request.GET, queryset=posts)
		queryset = self.myFilter.qs 
		#  [::-1] = to reverse the queryset
		return queryset[::-1]

	def get_context_data(self, **kwargs):
		ctx = super().get_context_data(**kwargs)
		ctx['myFilter'] = self.myFilter
		ctx['importantObjects'] = ForumPost.objects.all().filter(topic__icontains="Important")
		return ctx


# creating the new post
class CreateForumPost(LoginRequiredMixin, CreateView):
	template_name = 'forum/forum_create_post.html'
	model = ForumPost
	form_class = ForumPostForm
	success_url = reverse_lazy('forum:forum-index-page')

	def form_valid(self, form):
		form.instance.user = self.request.user
		# you can define in witch order you calling the super method
		return super().form_valid(form)

# updating the new post
class UpdateForumPost(OwnerUpdateView):
	template_name = 'forum/forum_update_post.html'
	model = ForumPost
	form_class = ForumPostForm
	success_url = reverse_lazy('forum:forum-index-page')

	def get_context_data(self, **kwargs):
		ctx = super().get_context_data(**kwargs) # run data from generic view first, then append here something else
		# going into super class
		return ctx

# deleting post
class DeleteForumPost(OwnerDeleteView):
	template_name = 'forum/forum_delete_post.html'
	model = ForumPost
	success_url = reverse_lazy('forum:forum-index-page')

# detail view of the post
class DetailForumPage(View):
	def getqueryrelation(self, request, post):
		# function that is taking everything that repeating in it. It is checking if user has a query relation with post. If he liked or disliked that post
		# also it checks, if user is authenticated
		if request.user.is_authenticated:
			query_relation = Reputation_post.objects.filter(user=request.user).filter(post=post).first()
			if query_relation is None:
				relation_value = 0
			else:
				relation_value = query_relation.reputation
		else:
			relation_value = None

		return relation_value

	def get(self, request, pk):

		post = get_object_or_404(ForumPost, id=pk)
		comments = CommentToPost.objects.all().filter(post_id=pk)
		form = CommentToPostForm
		ctx = {
		'post':post,
		'form':form,
		'comments':comments,
		'relation_value': self.getqueryrelation(request, post),
		}

		return render(request, 'forum/forum_detail_post.html', ctx)
	# creating comment functionality
	def post(self, request, pk):
		if request.user.is_authenticated:
			form = CommentToPostForm(request.POST)
			if form.is_valid():
				obj = form.save(commit=False)
				obj.user = request.user
				obj.post = get_object_or_404(ForumPost, pk=pk)
				obj.save()
				return redirect('forum:forum-detail-page', pk)
			else:
				return render(request, 'forum/forum_detail_post.html', ctx)
		else:
			ctx = {
			'post':post,
			'form':form,
			'comments':comments,
			'relation_value': self.getqueryrelation(request),
			}
			return render(request, 'forum/forum_detail_post.html', ctx)

# Ajax is here, because we need to set reputation for each post dynamicly
# the logic for reputation holded by ajax
class DetailForumPostPageAjax(LoginRequiredMixin, View):
	def post(self, request, pk):
		# here I need to check if user is already has opinion with post_reputation

		cur_user = User.objects.get(pk=request.POST["user_id"])
		post = ForumPost.objects.get(pk=request.POST["post_id"])
		user_action = request.POST["user_action"]
		# after when I got everything, I need to check if the user_profile has relation with ForumPostObject, called opinion_posts

		if user_action == 'dislike':
			reputation_temp = 1
		else:
			reputation_temp = -1
		query_relation = Reputation_post.objects.filter(user=cur_user).filter(post=post).first()
		counter = 0

		# check functionality for like and dislike buttons. Logic here are ment to check if user clicked same button two times and other scenarios

		if query_relation == None:
			if user_action == 'like':
				reputation_temp = 1
			elif user_action == 'dislike':
				reputation_temp = -1
			else:
				reputation_temp = 0
			new_relation = Reputation_post(user=cur_user, post=post, reputation=reputation_temp)
			post.people_voted += 1
			
			post.post_reputation += new_relation.reputation
			post.save()
			new_relation.save()
			query_relation = new_relation
		else:
			# so if reputation is greater then 0 we will check if
			if query_relation.reputation > 0:
				# it is like pressed, if so, undo the reputation and lover the people, that have been before
				if user_action == 'like':
					query_relation.reputation += -1
					counter = -1
					post.people_voted += -1
				# if it is dislike, we dont undo the people, but we changing the reputation
				elif user_action == 'dislike':
					query_relation.reputation += -2
					counter = -2
				else:
				# else we do nothing
					pass
			# else if the reputation is negative (means the dislike have been pressed before)
			elif query_relation.reputation < 0:
				# we will check, if it is a like, if so we won't change the count of people, inseted change reputation
				if user_action == 'like':
					query_relation.reputation += 2
					counter += 2
				# if dislike have been pressed the second time, we will undo dislike and lower the people
				elif user_action == 'dislike':
					query_relation.reputation += 1
					post.people_voted += -1
					counter +=1
				# else we do nothing
				else:
					pass
			# if the relation exist and it is 0 and something have been pressed we will change reputation and do nothing with people, because they are counted up
			else:
				if user_action == 'like':
					query_relation.reputation = 1
					counter += 1
					post.people_voted += 1
				elif user_action == 'dislike':
					query_relation.reputation = -1
					post.people_voted += 1
					counter -= 1
				else:
					pass			
			post.post_reputation += counter
			post.save()
			query_relation.save()
		

		# Create json object, that we sending back

		# I need to send something to dermine, which button should I show

		data = {
		"people_voted": post.people_voted,
		"reputation" : post.post_reputation,
		# send the value of query_relation.reputation
		"current_relation_reputation": query_relation.reputation
		}
		return JsonResponse(data)


# new advanced search
class fullSearch(View):
	# generate page with get method
	def get(self, request):
		return render(request, 'forum/fullsearch.html')

	def post(self, request):

		# getting everything from POST dictionary
		iD = request.POST['iD']
		name = request.POST['name']
		author = request.POST['author']
		topic = request.POST['topic']
		tags = request.POST['tags']

		# logic for parsing tags by comma

		tags_individual = tags.split(',')

		tags_url = ''
		for i in range(len(tags_individual)):
			tags_url += f'&tags={tags_individual[i]}'


		rating = request.POST['rating']
		lessrating = request.POST['lessrating']
		greatrating = request.POST['greatrating']


		contains = request.POST['contains']
		date_after = request.POST['date_after']
		date_before = request.POST['date_before']

		# construct url
		url = f'/forum/?id={iD}&name={name}&user__username={author}&topic={topic}{tags_url}&greatrating={greatrating}&rating={rating}&lessrating={lessrating}&text={contains}&start_date={date_after}&end_date={date_before}'
		# redirect
		return redirect(url)

		pass

# delete, edit comment functionality
# people protection functionality

class EditCommentToPost(OwnerUpdateView):
	template_name = 'forum/comment_edit_page.html'
	model = CommentToPost
	form_class = CommentToPostForm
	success_url = reverse_lazy('forum:forum-index-page')

class DeleteCommentToPost(OwnerDeleteView):
	template_name = 'forum/comment_delete_page.html'
	model = CommentToPost
	success_url = reverse_lazy('forum:forum-index-page')

forum/templates/forum/comment_delete_page.html
{% extends 'mainapp/base_template.html' %}
{% load crispy_forms_tags %}


{% block content %}
<article class="article-system">
<div class="row container-fluid ">
	<div class="col-md-2"></div>
	<div class="col-md-8 text-center bg-white mb-3 mt-3">
		<h1 class="text-primary mt-3">Delete comment</h1>
		<form class="p-3" method="POST">
			{% csrf_token %}

			<p class="mb-3 mt-3">Are you sure you want to delete this comment? You won't be able to restore it</p>

			<div class="mb-1 mt-3">
			<a class="btn btn-warning" href="{{request.META.HTTP_REFERER}}">Cancel</a><button class="btn btn-danger" type="submit">Delete</button>
			</div>
		</form>
	</div>
	<div class="col-md-2"></div>
</div>
</article>
{% endblock %}

forum/templates/forum/comment_edit_page.html
{% extends 'mainapp/base_template.html' %}
{% load crispy_forms_tags %}


{% block content %}
<article class="article-system">
<div class="row container-fluid ">
	<div class="col-md-2"></div>
	<div class="col-md-8 text-center bg-white mb-3 mt-3">
		<h1 class="text-primary mt-3">Edit comment</h1>
		<form class="p-3" method="POST">
			{% csrf_token %}

			{{form|crispy}}

			<div class="mb-1 mt-3">
			<a class="btn btn-warning" href="{{request.META.HTTP_REFERER}}">Cancel</a><button class="btn btn-primary" type="submit">Update changes</button>
			</div>
		</form>
	</div>
	<div class="col-md-2"></div>
</div>
</article>
{% endblock %}

forum/templates/forum/forum_create_post.html
{% extends 'mainapp/base_template.html' %}
{% load crispy_forms_tags %}

{% block content %}
<article>
<div class="row container-fluid">
	<div class="col-md-9 mb-3 mt-3">
		<div class="card card-body">
			<h1 class="text-primary">Create a new discussion</h1>
			<form method="POST" action="">
				{% csrf_token %}


				{{form.media}}



				{{form|crispy}}

				<input class="btn btn-primary" type="submit" name="" value="Create new discussion">
			</form>
		</div>
	</div>

	{% include 'forum/forum_navigation_sidebar.html' %}
</div>
</article>
{% endblock %}

forum/templates/forum/forum_delete_post.html
{% extends 'mainapp/base_template.html' %}

{% block content %}
<article class="container-fluid">
	<div class="row">
		<div class="col-md-9 card card-body mt-3 mb-3">
			<form method="POST" action="">
				{% csrf_token %}

				<p>Are you sure that you wanna to delete this post?</p>

				<a class="btn btn-warning" href="{{request.META.HTTP_REFERER}}">Cancel</a>

				<input class="btn btn-danger" type="submit" name="" value="Submit">

			</form>

		</div>

		{% include 'forum/forum_navigation_sidebar.html' %}
	</div>
</article>

{% endblock %}

forum/templates/forum/forum_detail_post.html
{% extends 'mainapp/base_template.html' %}
{% load static from static %}
{% load crispy_forms_tags %}


{% block content %}

<article class="mb-5">
	<div class="row container-fluid">

		<div class="col-md-9 mt-3">

			<div class="card card-body post forum-post-image">
				<hr>
				{% if post.topic == "Important" %}
				<h2 class="text-danger text-center card p-1">{{post.name}}</h2>
				{% else %}
				<h2 class="text-primary text-center card p-1">{{post.name}}</h2>
				{% endif %}
				<hr>
				<p class="">Topic: {{post.topic}}</p>
				<p class="">Tags: 
					<ul>
				        {% for tag in post.tags.all %}
				            <li class="tag"> {{ tag.name }} </li>
				        {% endfor %}
        			</ul>
    			</p>

    			<div style="align-items: center !important;">
    			<span class="float-start">Reputation: <span id="repa"><u>{{ post.post_reputation }}</u></span></span><br><span class="float-start"><span id="people_voted_counter"><u>{{ post.people_voted }}</u></span> people voted on this post</span>
    			<!-- кастыль -->
    			{% if user.is_authenticated %}

    			<div class="btn-toolbar pb-3" role="toolbar" aria-label="Toolbar with button groups">
	    			<div class="btn-group d-flex w-25 ms-auto" role="group" aria-label="Actions with post">
	    				<a class="btn btn-primary me-2" href="{% url 'mainapp:secutiry-report-bug' %}"><i class="fas fa-exclamation"></i></a>
	    				<button class="btn btn-success d-inline text-nowrap" onclick="onPostThumbs('{{request.user.id}}', '{{post.id}}', 'like')"><i id="like" class="{% if relation_value <= 0 %}far{% else %}fas{% endif %} fa-thumbs-up"></i></button>
	    				<button class="btn btn-danger d-inline text-nowrap" onclick="onPostThumbs('{{request.user.id}}', '{{post.id}}', 'dislike')"><i id="dislike" class="{% if relation_value >= 0 %}far{% else %}fas{% endif %} fa-thumbs-down"></i></button>
	    			</div>
    			</div>
    			{% else %}

    			{% endif %}
    			</div>
    			
    			<div class="card p-3">
    				{{post.content|safe}}
				</div>
				
				<div class="">
				<i class="p-3 float-end">{{post.date_created}}</i>
				<p class="p-3 fload-start" style="text-indent: 0;">Author: | <a href="{% url 'authentication:user-view-profile' post.user.id %}"><img class="profile-pic-small" src="{{post.user.user_profile.profile_picture.url}}" alt="Autor image"/></a> | <a href="{% url 'authentication:user-view-profile' post.user.id %}">{{post.user.username}}</a>{% if post.user.is_staff %} | <i class="fas fa-user-tie text-danger"></i>{% endif %} | <i class="fas fa-crown crown"></i></p>
				</div>
				<hr>
				<!-- comments -->
				{% if request.user.is_authenticated %}
				<form method="POST" action="">
					{% csrf_token %}
					{{form|crispy}}
					<input class="btn btn-light mt-3" type="submit" name="" value="Post a comment">
				</form>
				{% else %}
				{{next}}

				To be able to write a comment please <a href="{% url 'authentication:login' %}?next={{request.path}}">Login</a>
				{% endif %}

				<!-- comments -->

				<hr>
				Comments ({{ comments.count }})
				<hr>

				{% for comment in comments reversed %}
				<div class="comment">
					<div class="">
						<a href="{% url 'authentication:user-view-profile' comment.user.id %}"><img class="comment-image" src="{{comment.user.user_profile.profile_picture.url}}" alt="Profile Image"></a>
					</div>
					<div class="">
						<div class="comment-nick" style="align-items: center;"><span class="text"><a href="{% url 'authentication:user-view-profile' comment.user.id %}">{{comment.user.username}}</a> {% if comment.user.is_staff %} | <i class="fas fa-user-tie text-danger"></i>{% endif %} {% if comment.user == post.user %}| <i class="fas fa-crown crown"></i>{% endif%}</span>
						
						<span class="comment-date-posted">{{ comment.date_created }}</span><i class="fas fa-clock comment-date-posted pe-1"></i>{% if request.user == comment.user or request.user.is_staff %} <a href="{% url 'forum:forum-delete-comment-post' comment.id %}"><i class="fas fa-times text-danger comment-date-posted pe-1"></i></a><a href="{% url 'forum:forum-edit-comment-post' comment.id %}"><i class="fas fa-edit comment-date-posted pe-1"></i></a>{% endif %}
						</div>
						<p class="card comment-text"> {{comment.text}} </p>
					</div>
				</div>
				{% endfor %}
			</div>

		</div>
		{% include 'forum/forum_navigation_sidebar.html' %}
	</div>
</article>




{% endblock %}

forum/templates/forum/forum_navigation_sidebar.html
<div class="col-md-3 mt-3">
	<div class="card card-body phone-hide sticky-sidebar">
		<h2>Forum<br>Navigation</h2>
		<hr>
		<div class="btn-group d-grid" role="group" aria-label="Right side bar user management">
				<div class="btn-group-vertical" role="group" aria-label="Vertical button group">
				{% if user.is_authenticated %}
				<button class="btn btn-dark" disabled>User: {{ user.get_username }} <i class="fas fa-user ms-1"></i></button>
				<a href="{% url 'authentication:user-profile' %}" class="btn btn-primary">Account Preferences<i class="fas fa-cog ms-1"></i></a>
				<a  href="{% url 'authentication:logout'%}" class="btn btn-primary">Logout<i class="fas fa-sign-out-alt ms-1"></i></a>
				{% else %}  
				  <a href="{% url 'authentication:register-new-user-page' %}?next={{request.path}}" class="btn btn-success">Sign up <i class="fas fa-user-plus ms-1"></i></a>
				  <a href="{% url 'authentication:login'%}?next={{request.path}}" class="btn btn-primary">Login <i class="fas fa-sign-in-alt ms-1"></i></a>
				{% endif %}
				</div>
			</div>
		{% if request.user.is_authenticated %}
		<hr>
		<div class="btn-group d-grid" role="group" aria-label="Forum side bar preferences of the forum">
			<div class="btn-group-vertical" role="group" aria-label="Vertical button group">

			{% url 'forum:forum-create-post' as forum_create_post_url %}
			{% if request.path != forum_create_post_url %}
			<a class="btn btn-success" href="{% url 'forum:forum-create-post' %}">Create New Forum post +</a>
			{% endif %}
			
			<a class="btn btn-info" href="{% url 'forum:forum-index-page' %}?name&user_username={{request.user.username}}">View my posts <i class="far fa-eye ms-2"></i></a>
			
			{% url 'forum:forum-detail-page' post.id as forum_detail_post_url %}
			

			{% if request.path != forum_create_post_url and request.path != forum_detail_post_url %}
				{% if request.user.id == object.user.id or request.user.is_staff %}

					<a class="btn btn-warning" href="{% url 'forum:forum-update-post' object.id %}">Edit post <i class="fas fa-edit ms-1"></i></a>
					<a class="btn btn-danger" href="{% url 'forum:forum-delete-post' object.id %}">Delete post <i class="fas fa-trash-alt ms-1"></i></a>

				{% endif %}
			{% endif %}

			<!-- fix for detail, cause it has other queryset and variables -->

			{% if request.path == forum_detail_post_url %}
			{% if request.user.id == post.user.id or request.user.is_staff %}
			<a class="btn btn-warning" href="{% url 'forum:forum-update-post' post.id %}">Edit post <i class="fas fa-edit ms-1"></i></a>
			<a class="btn btn-danger" href="{% url 'forum:forum-delete-post' post.id %}">Delete post <i class="fas fa-trash-alt ms-1"></i></a>
			{% endif %}
			{% endif %}
			{% endif %}


			</div>
		</div>

		{% if request.user.is_staff %}
		<hr>

		<div class="btn-group d-grid" role="group" aria-label="Admin panel">
		<div class="btn-group-vertical" role="group" aria-label="Vertical button group">
		
		<a class="btn btn-danger" href="{% url 'admin:index' %}">Admin panel <i class="fas fa-tools ms-1"></i></a>
		</div>
		</div>
		{% endif %}
	</div>
</div>

forum/templates/forum/forum_update_post.html
{% extends 'mainapp/base_template.html' %}
{% load crispy_forms_tags %}


{% block content %}
<article>
<div class="row container-fluid">
	<div class="col-md-9 mt-3 mb-3">
		<div class="card card-body">
		<form method="POST" action="">
			{% csrf_token %}

			{{form.media}}

			{{form|crispy}}

			<input class="btn btn-primary" type="submit" name="" value="Update changes">
			</form>
		</div>
	</div>

	{% include 'forum/forum_navigation_sidebar.html' %}
</div>
</article>
{% endblock %}