authentication/urls.py
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.urls import path
from . import views
from . forms import *
from django.urls import path, include

app_name = 'authentication'

# Urls for authentication app

urlpatterns = [
	path('register/', views.RegistrationPage.as_view(), name='register-new-user-page'),
	path('login/',
		auth_views.LoginView.as_view(authentication_form=AuthenticationForm, template_name="authentication/login.html"),
		name="login"),
	path('logout/',
		auth_views.LogoutView.as_view(template_name="authentication/login.html"),
		name="logout"),	
    path('reset_password/',
     	auth_views.PasswordResetView.as_view(template_name="authentication/password_reset_form.html", email_template_name="authentication/password_reset_email.html", success_url=reverse_lazy("authentication:password_reset_done")), 
    	name="reset_password",),

    path('reset_password_sent/', 
    	auth_views.PasswordResetDoneView.as_view(template_name="authentication/password_reset_done.html"), 
    	name="password_reset_done"),
    
    path('reset/<uidb64>/<token>/', 
    	auth_views.PasswordResetConfirmView.as_view(template_name="authentication/password_reset_confirm.html", success_url=reverse_lazy("authentication:password_reset_complete") ), 
    	name="password_reset_confirm"),
    
    path('reset_password_complete/', 
    	auth_views.PasswordResetCompleteView.as_view(template_name="authentication/password_reset_complete.html"), 
    	name="password_reset_complete"),	

	path('profile/', views.UserProfile.as_view(), name='user-profile'),

	path('profile/<str:pk>/', views.ViewProfilePage.as_view(), name='user-view-profile'),

    path('profile/<str:pk>/ajax/', views.ViewProfilePageAJAX.as_view()),
]

bowcraftorg/urls.py
from django.contrib import admin
from django.urls import path, include
# doing data because need to set up static url
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, re_path


# rest framework
from rest_framework import routers

from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
# from ckeditor_uploader import views as ckeditor_views

# This file is main file for our project urls

# rest framework
router = routers.DefaultRouter()

# Here we have url paths to all our applications

# Apps, that we are using: admin app, authenication, forum, mainappp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/', include('django_admin_filter.urls')),
    path('', include('mainapp.urls')),
    path('user/', include('authentication.urls')),
    path('forum/', include('forum.urls')),
    path('ckeditor/', login_required(include('ckeditor_uploader.urls'))),
    # path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api/', include(router.urls)),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Here we add other paths to our project, like captcha, Mediroot, 404 page

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

def test_404_view(request):
    raise Http404("Page not found")

urlpatterns += [
    path('test-404/', test_404_view, name='test_404_view'),
]

forum/urls.py
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.urls import path
from . import views
from django.urls import path, include

app_name = 'forum'

# All urls routes for forum application
# We can see forum page, create post, update post, delete post, view details of post, search for post, comment, edit delete comment, ajax for post reputation

urlpatterns = [
	path('', views.ForumIndexPage.as_view(), name="forum-index-page"),
	path('create/', views.CreateForumPost.as_view(), name="forum-create-post"),
	path('update/<str:pk>/', views.UpdateForumPost.as_view(), name="forum-update-post"),
	path('delete/<str:pk>/', views.DeleteForumPost.as_view(), name="forum-delete-post"),
	path('post/<str:pk>/', views.DetailForumPage.as_view(), name='forum-detail-page'),
	path('search/', views.fullSearch.as_view(), name='forum-search'),
	path('comment/edit/<str:pk>/', views.EditCommentToPost.as_view(), name='forum-edit-comment-post'),
	path('comment/delete/<str:pk>/', views.DeleteCommentToPost.as_view(), name='forum-delete-comment-post'),
	path('post/<str:pk>/ajax/', views.DetailForumPostPageAjax.as_view()),
]

mainapp/urls.py
from django.urls import path
from . import views

# This file contains all urls for our mainapp

app_name = 'mainapp'

# Home page with presentaion, news page, support us page, download page, individual news post page, contact page
# contact confirm message send page, security report url and security security success message sent
urlpatterns = [
	path('', views.HomePage.as_view(), name='home-page'),
	path('news/', views.NewsPage.as_view(), name='news-page'),
	path('news/all/', views.NewsAllPage.as_view(), name='news-all'),
	path('support/us/', views.SupportUs.as_view(), name='support-us-page'),
	path('download/', views.DownloadPage.as_view(), name='download-page'),
	path('post/<str:pk>/', views.PostDetailPage.as_view(), name='post-detail'),
	path('contact/', views.ContactPage.as_view(), name='contact-page'),
	path('contact/confirm', views.ConfirmPage.as_view(), name='confirm-contact-page'),
	path('security/report', views.SecurityContactPage.as_view(), name='secutiry-report-bug'),
	path('security/success/', views.SuccessSecurityPage.as_view(), name='secutiry-report-success'),
]

mainapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django_ckeditor_5.fields import CKEditor5Field

# This file contains all database talbes for our mainapp


# -------------------------------------------- ckeditor
class Article(models.Model):
    title=models.CharField('Title', max_length=200)
    text=CKEditor5Field('Text', config_name='extends')
# ck eidotr -------------------------------------------


# This our post talbe for news
class Post(models.Model):
	name = models.CharField(max_length=30, null=True)
	text = CKEditor5Field(null=True, blank=True)
	preview_text = models.CharField(max_length=400, null=True, blank=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True)
	preview_picture = models.ImageField(default="home_posts/sample_image.jpg", null=True, blank=True)

	def __str__(self):
		return self.name

# comment on post table
class CommentToPost(models.Model):
	user = models.ForeignKey(User, related_name="user_comment_news", blank=True, null=True, on_delete=models.CASCADE)
	post = models.ForeignKey(Post, related_name="post_comment_news", blank=True, null=True, on_delete=models.CASCADE)
	text = models.TextField(null=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True)

	def __str__(self):
		return str(self.date_created) + ' ' + self.post.name + ' ' + self.user.username

# contact us with email table
class ContactEmail(models.Model):
	email = models.EmailField(max_length=30, null=True)
	subject = models.CharField(max_length=50, null=True)
	text = models.TextField(null=True)
	date_sent = models.DateTimeField(auto_now_add=True, null=True)

	def __str__(self):
		return self.subject + ' ' + self.email

# Security report table
class SecurityEmailMessage(models.Model):
	CATEGORY = (
		('Bug on website', 'Bug on website'),
		('Violation', 'Violation'),
		('Suggestions', 'Suggestions'),
		('Help', 'Help'),
		('Bug on server','Bug on server'),
		('Bug with plugins', 'Bug with plugins'),
		('Other', 'Other'),
	)
	email = models.EmailField(max_length=30, null=True)
	subject = models.CharField(max_length=50, null=True)
	topic = models.CharField(max_length=100, null=True, choices=CATEGORY)
	text = CKEditor5Field(null=True)
	date_sent = models.DateTimeField(auto_now_add=True, null=True)

	def __str__(self):
		return self.subject + ' ' + self.topic + ' ' + self.email

mainapp/forms.py
from django import forms
from django.forms import ModelForm
from captcha.fields import CaptchaField
from . models import *

# This file contains 3 form four our tables for: comment for news, contact e-mail table and report message  

class CommentToPostForm(ModelForm):
	text = forms.CharField(widget=forms.Textarea, label='')
	class Meta:
		model = CommentToPost
		fields = ['text']

class ContactEmailsForm(ModelForm):
	
	class Meta:
		model = ContactEmail
		fields= '__all__'
		exclude = ('date_sent',)
		

class SecutiryMainForm(ModelForm):
	captcha = CaptchaField()
	class Meta:
		model = SecurityEmailMessage
		fields = '__all__'
		exclude = ('date_sent',)
		

mainapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.views import generic
from django.views import View
from django.http import Http404

from . models import *
from . forms import *
from . filters import *

# This file contains all logic for our news feed and mainapp
# Views file

# detail view of the post
class PostDetailPage(View):
	def get(self, request, pk):

		post = get_object_or_404(Post, id=pk)
		comments = CommentToPost.objects.all().filter(post_id=pk)
		form = CommentToPostForm
		ctx = {
		'post':post,
		'form':form,
		'comments':comments,
		}
		return render(request, 'mainapp/post_detail.html', ctx)
	def post(self, request, pk):
		if request.user.is_authenticated:
			form = CommentToPostForm(request.POST)
			if form.is_valid():
				obj = form.save(commit=False)
				obj.user = request.user
				obj.post = get_object_or_404(Post, pk=pk)
				obj.save()
				return redirect('mainapp:post-detail', pk)
			else:
				return render(request, 'mainapp/post_detail.html', ctx)
		else:
			ctx = {
			'post':post,
			'form':form,
			'comments':comments,
			}
			return render(request, 'mainapp/post_detail.html', ctx)

# home page
class HomePage(View):
	def get(self, request):
		return render(request, 'mainapp/home_page.html')

# newspage
class NewsPage(generic.ListView):
	template_name = 'mainapp/home.html'
	paginate_by = 5
	model = Post

	def get_queryset(self):
		self.news_count = Post.objects.all().count()
		queryset = super(NewsPage, self).get_queryset()
		# reverse queryset
		return queryset[::-1]

	def get_context_data(self, **kwargs):
		ctx = super().get_context_data(**kwargs)
		ctx['news_count'] = self.news_count
		return ctx

# All news page
class NewsAllPage(generic.ListView):
	template_name = 'mainapp/news_all.html'
	model = Post
	def get_queryset(self):
		news = Post.objects.all()
		# filter all usernames
		queryset = super(NewsAllPage, self).get_queryset()


		self.myFilter = newsFilter(self.request.GET, queryset=news)
		
		queryset = self.myFilter.qs 
		return queryset

	def get_context_data(self, **kwargs):
		ctx = super().get_context_data(**kwargs)
		ctx['myFilter'] = self.myFilter
		return ctx


# about page
class AboutPage(View):
	def get(self, request):
		return render(request, 'mainapp/about_page.html')

# support us page
class SupportUs(View):
	def get(self, request):
		return render(request, 'mainapp/support_us_page.html')

# download page
class DownloadPage(View):
	def get(self, request):
		return render(request, 'mainapp/download_page.html')



# footer contact form + contact form in contact form view
class ContactPage(FormView):
	def get(self, request):
		form = ContactEmailsForm()
		ctx = {
		'form':form,
		}
		return render(request, 'mainapp/contact_page.html', ctx)
	def post(self, request):
		form = ContactEmailsForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('mainapp:confirm-contact-page')
		else:
			ctx = {
			'form':form,
			}
			return render(request, 'mainapp/contact_page.html', ctx)
		# save email to the database


# if the user sended their mail correct, they would be redirected to the confirmed view
class ConfirmPage(View):
	def get(self, request):
		return render(request, 'mainapp/contact_confirm_page.html')



# view of the security page
class SecurityContactPage(FormView):
	def get(self, request):
		form = SecutiryMainForm()
		ctx = {
		'form':form,
		}
		return render(request, 'mainapp/security_bug_send.html', ctx)
	def post(self, request):
		form = SecutiryMainForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('mainapp:secutiry-report-success')
		else:
			ctx = {
			'form':form,
			}
			return render(request, 'mainapp/security_bug_send.html', ctx)

# success security page view
class SuccessSecurityPage(View):
	def get(self, request):
		return render(request, 'mainapp/security_success.html')

def page_not_found(request, exception):
	response = render_to_response('404.html',context_instance=RequestContext(request))
	response.status_code = 404
	return response

mainapp/templates/mainapp/footer.html
{% load static from static %}

<!-- Footer -->
<footer class="bg-dark text-center text-white">
  <!-- Grid container -->
  <div class="container p-4">




    <!-- Section: Links -->
    <section class="">
      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">About Us</h5>

            <p>
                Bowcraft is amazing pre-configured minecraft server. You can download and use it. It is completele free, delivered by MIT licence.
            </p>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase mb-3">Navigation</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a href="{% url 'mainapp:home-page' %}" class="text-white">Home</a>
            </li>
            <li>
              <a href="{% url 'forum:forum-index-page' %}" class="text-white">Forum</a>
            </li>
            <li>
              <a href="{% url 'mainapp:download-page' %}" class="text-white">Download</a>
            </li>
            <li>
              <a href="{% url 'mainapp:support-us-page' %}" class="text-white">Support Us</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase mb-3">Social media</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a href="https://github.com/alekseispolysov/Bowstal-Craft" class="text-white"><i class="fab fa-github me-1"></i>Github</a>
            </li>
            <li>
              <a href="#!" class="text-white"><i class="fab fa-facebook-f me-1"></i>Facebook</a>
            </li>
            <li>
              <a href="#!" class="text-white"><i class="fab fa-discord me-1"></i>Discord</a>
            </li>
            <li>
              <a href="#!" class="text-white"><i class="fab fa-instagram me-1"></i>Instagram</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Contact Us</h5>

        <form method="POST" action="{% url 'mainapp:contact-page' %}">
            {% csrf_token %}
            <ul>        
                <li><label for="email">Your email address: </label><br><input name="email" type="text" id="email"></li>
                <li><label for="subject">Subject: </label><br><input name="subject" type="text" id="subject"></li>
                <li><label for="textarea">Text of email: </label><br><textarea name="text" id="textarea"></textarea></li>
                <li><br><input class="btn btn-primary btn-lg rounded-pill" type="submit" name="" value="Submit"></li>
            </ul>
        </form>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </section>
    <!-- Section: Links -->

  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    &#169; copyright
    <a class="text-white" href="{% url 'mainapp:home-page' %}">BowStalCraft</a> <script>document.write(new Date().getFullYear());</script>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

mainapp/templates/mainapp/footer_dublicate.html
{% load static from static %}

    <footer class="footer container-fluid">
        <div class="row">
            <div class="col-md-3">
                <h3>About Us</h3>
                <p><a href="{% url 'mainapp:home-page' %}"><img src="{% static 'images/logo.png' %}" class="navbar-brand navbar-brand-image-size"></a>
                
                    Bowcraft is amazing server, try it out right now! We are waiting for you all the time!
                    There is always stuff overhere and it is completely free. What could possibly go wrong?
                </p>
            </div>
            <div class="col-md-3">
                <h3>Navigation</h3>
                <ul>
                    <li><a href="{% url 'mainapp:home-page' %}">Home</a></li>
                    <li><a href="{% url 'forum:forum-index-page' %}">Forum</a></li>
                    <li><a href="{% url 'mainapp:download-page' %}">Download</a></li>
                    <li><a href="{% url 'mainapp:support-us-page' %}">Support Us</a></li>
                    <li><a href="">Search</a></li>
                    <li><a href="{% url 'mainapp:about-page' %}">About</a></li>
                </ul>
            </div>
            <div class="col-md-3">
                <h3>Social Media</h3>
                <ul>
                    <li><img src="{% static 'images/logos_copyright/facebook-logo.png' %}" class="foter_image"><a href="">Facebook</a></li>
                    <li><img src="{% static 'images/logos_copyright/vk-reproductor.png' %}" class="foter_image"><a href="">VK</a></li>
                    <li><img src="{% static 'images/logos_copyright/instagram-logo.png' %}" class="foter_image"><a href="">Instagram</a></li>
                    <li><img src="{% static 'images/logos_copyright/discord.png' %}" class="foter_image"><a href="">Discord</a></li>
                    <li><img src="{% static 'images/logos_copyright/reddit-logo.png' %}" class="foter_image"><a href="">Reddit</a></li>
                </ul>
            </div>
            <div class="col-md-3">
                <h3>Contact Us</h3>
                <form method="POST" action="{% url 'mainapp:contact-page' %}">
                    {% csrf_token %}
                    <ul>        
                        <li><label for="email">Your email address: </label><br><input name="email" type="text" id="email"></li>
                        <li><label for="subject">Subject: </label><br><input name="subject" type="text" id="subject"></li>
                        <li><label for="textarea">Text of email: </label><br><textarea name="text" id="textarea"></textarea></li>
                        <li><br><input class="btn btn-light" type="submit" name="" value="Submit"></li>
                    </ul>
                </form>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 text-center">
                    Bowcraft copyright &#169; <script>document.write(new Date().getFullYear());</script>
                </div>
            </div>
        </div>
    </footer>

mainapp/templates/mainapp/left_side_bar.html
<div class="col-md-3">
	<div class="card card-body phone-hide sticky-sidebar">
		{% url 'mainapp:news-page' as url_news %}
		{% if request.path == url_news %}
		<h2>Post History</h2>
		
		<hr>
		<table class="table table-striped table-hover ">
		{% for post in object_list %}
		<tr class="">
			<td class="h-25 text-center" style="padding: 10px !important;">
				
				<a class="text-center" href="{% url 'mainapp:post-detail' post.id %}">{{ post.name }}</a>
				
			</td>
		</tr>
		{% endfor %}
		</table>	
		<a class="btn btn-primary" href="{% url 'mainapp:news-all' %}">Show all ({{ news_count }})</a>
		{% else %}
		<h2>News navigation</h2>
		<hr>
		<a class="btn btn-primary" href="{% url 'mainapp:news-page' %}">News page</a>
		<a class="btn btn-info" href="{% url 'mainapp:news-all' %}">All news</a>
		<a href="{{request.META.HTTP_REFERER}}" class="btn btn-warning">Go back</a>
		{% endif %}
	</div>
</div>

mainapp/templates/mainapp/navbar.html
{% load static from static %}



<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark" >
  <div class="container-fluid">
    <a href="{% url 'mainapp:home-page' %}"><img src="{% static 'images/B-letter.jpg' %}" class="navbar-brand navbar-brand-image-size"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- allign navbar to center -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" display="hidden"> 
      </ul>
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
        {% url 'mainapp:news-page' as url_news %}
        <li>
          <a class="nav-link {% if request.path == url_news %}active{% endif %}" href="{{url_news}}">News</a>
        </li>
        {% url 'forum:forum-index-page' as url_forum %}
        <li>
          <a class="nav-link {% if request.path == url_forum %}active{% endif %}" href="{{url_forum}}">Forum</a>
        </li>
        {% url 'mainapp:download-page' as url_download %}
        <li>
          <a class="nav-link {% if request.path == url_download %}active{% endif %}" href="{{url_download}}">Download</a>
        </li>
        {% url 'mainapp:support-us-page' as url_support %}
        <li>
          <a class="nav-link {% if request.path == url_support %}active{% endif %}" href="{{url_support}}">Support Us</a>
        </li>
        {% url 'mainapp:contact-page' as url_contact %}
        <li>
          <a class="nav-link {% if request.path == url_contact %}active{% endif %}" href="{{url_contact}}">Contact Us</a>
        </li>
        
      </ul>
         
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        {% if url_forum in request.path %}
        <li><a id="scroll-top" href="javascript:;" class="nav-link"><i class="fas fa-arrow-up"></i></a></li>
        <li class="me-1"><a id="scroll-bot" href="javascript:;" class="nav-link"><i class="fas fa-arrow-down"></i></a></li>
        {% endif %}
        {% if request.user.is_authenticated %}
        {% url 'authentication:user-profile' as url_user_profile %}
        <li>
          <a class="nav-link {% if request.path == url_user_profile %}active{% endif %}" href="{{url_user_profile}}">Account</a>
        </li>
        <!-- this is chat messages here, add when user is on this url change color to white -->
        {% if request.user.is_staff %}
        <li>
          <a class="nav-link btn btn-sm btn-danger rounded-pill" href="{% url 'admin:index' %}">Admin Panel</a>
        </li>
        {% endif %}     
        {% else %}
        {% url 'authentication:login' as url_login %}
        <li>
          <a class="btn btn-sm btn-light rounded-pill {% if request.path == url_login %}active{% endif %}" href="{{url_login}}">Login</a>
        </li>
        {% url 'authentication:register-new-user-page' as url_register %}
        <li>
          <a class="btn btn-sm btn-primary rounded-pill {% if request.path == url_register %}active{% endif %}" href="{{url_register}}">Sign Up</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

mainapp/templates/mainapp/navbar_backup.html
{% load static from static %}


<div class="container-image">
    <h1 class="text-on-imagetop-left sized-h1">BowStalCraft</h1>
    <nav class="navbar navbar-expand-lg navbar-dark navbar-transperensy text-on-image-top">
      <div class="container-fluid">
        <a href="{% url 'mainapp:home-page' %}"><img src="{% static 'images/logo.png' %}" class="navbar-brand navbar-brand-image-size"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- allign navbar to center -->
          <ul class="navbar-nav me-auto mb-2 mb-lg-0" display="hidden"> 
          </ul>
          <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
            {% url 'mainapp:news-page' as url_news %}
            <li>
              <a class="nav-link {% if request.path == url_news %}active{% endif %}" href="{{url_news}}">News</a>
            </li>
            {% url 'forum:forum-index-page' as url_forum %}
            <li>
              <a class="nav-link {% if request.path == url_forum %}active{% endif %}" href="{{url_forum}}">Forum</a>
            </li>
            {% url 'mainapp:download-page' as url_download %}
            <li>
              <a class="nav-link {% if request.path == url_download %}active{% endif %}" href="{{url_download}}">Download</a>
            </li>
            {% url 'mainapp:support-us-page' as url_support %}
            <li>
              <a class="nav-link {% if request.path == url_support %}active{% endif %}" href="{{url_support}}">Support Us</a>
            </li>
            {% url 'mainapp:contact-page' as url_contact %}
            <li>
              <a class="nav-link {% if request.path == url_contact %}active{% endif %}" href="{{url_contact}}">Contact Us</a>
            </li>
            {% url 'mainapp:about-page' as url_about %}
            <li>
              <a class="nav-link {% if request.path == url_about %}active{% endif %}" href="{{url_about}}">About</a>
            </li>
          </ul>
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            {% if request.user.is_authenticated %}
            {% url 'authentication:user-profile' as url_user_profile %}
            <li>
              <a class="nav-link {% if request.path == url_user_profile %}active{% endif %}" href="{{url_user_profile}}">Account</a>
            </li>
            {% if request.user.is_staff %}
            <li>
              <a class="nav-link text-danger" href="{% url 'admin:index' %}">Admin Panel</a>
            </li>
            {% endif %}     
            {% else %}
            {% url 'authentication:login' as url_login %}
            <li>
              <a class="nav-link {% if request.path == url_login %}active{% endif %}" href="{{url_login}}">Login</a>
            </li>
            {% url 'authentication:register-new-user-page' as url_register %}
            <li>
              <a class="nav-link {% if request.path == url_register %}active{% endif %}" href="{{url_register}}">Sign Up</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    
    <img id="header-image"  src="{% static 'images/minecraft.png' %}">
</div>

mainapp/templates/mainapp/security_bug_send.html
{% extends 'mainapp/base_template.html' %}
{% load static from static %}
{% load crispy_forms_tags %}

{% block content %}

<article class="article-system">
	<div class="pb-4 pt-3">
		<div class="row container-fluid gx-3">
			<div class="col-sm-5 mx-auto m-2 p-3 mb-3 border article-system-bg-white">
				<h2 class="text-primary text-center">Report an issue</h2>
				<hr>
				<form method="POST" action="{% url 'mainapp:secutiry-report-bug' %}">
					{% csrf_token %}
					{{form.media|safe}}
					{{form|crispy|safe}}
					<div class="mt-3">
						<button type="submit" class="btn btn-primary text-end">Submit</button>
					</div>
				</form>
				<hr>
				

			</div>
			<div class="col-sm-5 mx-auto m-2 p-3 mb-3 border article-system-bg-white">
				<img class="rounded mx-auto d-block image_resize" src="{% static 'images/lock.png' %}">	
				<p class="mt-3">
					You can report an issue by using the form on this page. Alternatively you can use our <a href="">discord</a> or ask a question on our <a href="{% url 'forum:forum-index-page' %}">forum</a>
				</p>
				<p>Rules for reporting:</p>
				<ul>
					<li>Do not report for no reason</li>
					<li>If you unsure ask a question in our <a href="">discord channel</a></li>
					<li>Be polite and constructive, when writing a report</li>
					<li>Try to reduce the number of grammatical errors, when you are finish</li>
				</ul>
			</div>
		</div>
	</div>
</article>

{% endblock %}